-- Create database
CREATE DATABASE IF NOT EXISTS uber_analytics;

USE uber_analytics;

-- Create trips table
CREATE TABLE IF NOT EXISTS uber_trips (
    START_DATE DATETIME,
    END_DATE DATETIME,
    CATEGORY VARCHAR(50),
    START_LOCATION VARCHAR(100),
    STOP_LOCATION VARCHAR(100),
    MILES DECIMAL(10,2),
    PURPOSE VARCHAR(100),
    MONTH INT,
    DAY_OF_WEEK VARCHAR(20),
    HOUR INT,
    DISTANCE_TYPE VARCHAR(20)
);